---
:create_dirs:
  - ~/bin
  - ~/src
  - ~/tmp
  - ~/.ssh
  - ~/.vim-undo
  - ~/.vim-swap
  - ~/.zsh.after
  - ~/.zsh.before
:simple_symlinks:
  - .ackrc
  - .colordiffrc
  - .dir_colors
  - .gitconfig
  - .gitglobalignore
  - .hgrc
  - .screen.development
  - .screenrc
  - .tmux.conf
  - .vim
  - .vimrc
:zsh_symlinks:
  - .zprezto
  - .zpreztorc
  - .zshrc
  - .zshplugins
  - .zsh.prompts
:subdir_symlinks:
  - bin
  - src
  - .ssh
:merged_configs:
  :sshconfig:
    :dst: .ssh/config
    :sys_src: .ssh_config
    :usr_src: .ssh_config.private
:homebrew_packages:
  - cscope
  - ctags
  - coreutils
  - curl
  - fasd
  - gist
  - git
  - hub
  - mercurial
  - rbenv
  - ruby-build
  - screen
  - tmux
  - tree
  - unzip
  - wget
  - zsh
:gems:
  - bundler
  - cheat
  - chronic
  - chronic_duration
  - facter
  - github-markup
  - jekyll
  - jeweler
  - kramdown
  - mustache
  - pry
  - rake
  - RedCloth
  - redcarpet
  - rspec
  - terminal-table
  - thor
  - yard
